apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service # Nama unik untuk objek Service
  labels:
    app: karsajobs  # Label yang diberikan pada Service
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31000
  selector:
    app: karsajobs  # Sesuaikan dengan label pod Karsajobs Anda
    tier: backend
