apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # username admin (base64)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # password supersecretpassword (base64)